name: reviewdog
on:
  push:
    branches: 
      - master
      - test*
  pull_request:
    branches: [ master ]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: toko-bifrost/ms-teams-deploy-card@master
          if: always()
          with:
            github-token: ${{ secrets.github_token }}
            webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}

      - uses: maratimaev/Bucket@master
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check, github-pr-review].
          reporter: github-pr-review
          fail_on_error: true 
          # Change reporter level if you need [info,warning,error].
          # GitHub Status Check won't become failure with a warning.
          level: warning          

      - uses: toko-bifrost/ms-teams-deploy-card@master
          if: always()
          with:
            github-token: ${{ secrets.github_token }}
            webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}

#      - uses: actions/checkout@master
#      - name: Microsoft Teams Notification
#        uses: skitionek/notify-microsoft-teams@master
#        if: success()
#        with:
#          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
#          needs: ${{ toJson(needs) }}
#          job: ${{ toJson(job) }}
#          steps: ${{ toJson(steps) }}

#      - uses: actions/checkout@v2
#      - name: Microsoft Teams Deploy Card
#        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
#        if: always()
#        with:
#          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
#          github-token: ${{ github.token }}
#          environment: None
#          timezone: "Asia/Kolkata"
##          card-layout-start: compact
#          card-layout-exit: complete
#          show-on-start: false
#          show-on-exit: true
#          custom-facts: |
#            - name: Repository
#              value: ${{github.repository}}
#            - name: ImageTag
#              value: ${{ github.sha }}
#          enable-view-status-action: true
#          enable-review-diffs-action: true
#          view-status-action-text: "View Status"
